using ChangeDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ChangeDB.Contexts.ETC;

public class AdminTripETConfiguration : IEntityTypeConfiguration<AdminTrip>
{
    public void Configure(EntityTypeBuilder<AdminTrip> entityTypeBuilder)
    {
        entityTypeBuilder.ToTable("Admin.TripsLobby");
        entityTypeBuilder.Property(p => p.TripId).HasColumnType("BIGINT").ValueGeneratedOnAdd();
        entityTypeBuilder.Property(p => p.BookId).HasColumnType("uniqueidentifier").ValueGeneratedOnAdd();
        entityTypeBuilder.HasKey(p => new { p.TripId, p.BookId });
        //entityTypeBuilder.Property(p => p.DriverId).HasColumnType("INT");
        //entityTypeBuilder.Property(p => p.DriverCode).HasColumnType("NVARCHAR(32)").IsRequired(false);
        //entityTypeBuilder.Property(p => p.VehicleId).HasColumnType("BIGINT");
        //entityTypeBuilder.Property(p => p.VehiclePlate).HasColumnType("VARCHAR(16)").IsRequired(false);
        //entityTypeBuilder.Property(p => p.CompanyId).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.Distance).HasColumnType("DECIMAL(18,2)").IsRequired(false);
        //entityTypeBuilder.Property(p => p.Send).HasColumnType("BIT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.SendTime).HasColumnType("DATETIME").IsRequired(false);
        //entityTypeBuilder.Property(p => p.Chosen).HasColumnType("BIT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.DriverState).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.DriverConfirm).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.Reason).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.ConfirmTime).HasColumnType("DATETIME").IsRequired(false);
        //entityTypeBuilder.Property(p => p.OperationId).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.Money).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.Lat).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.Lng).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.SendCatchedUser).HasColumnType("BIT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.DateSendCatchedUser).HasColumnType("DATETIME").IsRequired(false);
        //entityTypeBuilder.Property(p => p.SendInvite).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.DateSendInvite).HasColumnType("DATETIME").IsRequired(false);
        //entityTypeBuilder.Property(p => p.ReasonState).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.UserPath).HasColumnType("NVARCHAR(500)").IsRequired(false);
        //entityTypeBuilder.Property(p => p.DriverPath).HasColumnType("NVARCHAR(500)").IsRequired(false);
        //entityTypeBuilder.Property(p => p.Timeout).HasColumnType("BIT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.SourceType).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.DateDriverCancel).HasColumnType("DATETIME").IsRequired(false);
        //entityTypeBuilder.Property(p => p.DateDriverDone).HasColumnType("DATETIME").IsRequired(false);
        //entityTypeBuilder.Property(p => p.BlackBoxLostGSM).HasColumnType("BIT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.CancelType).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.TotalKm).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.TotalInvite).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.Offer).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.DriverCancelMsg).HasColumnType("NVARCHAR(500)").IsRequired(false);
        //entityTypeBuilder.Property(p => p.ReturnTripId).HasColumnType("uniqueidentifier").ValueGeneratedNever().IsRequired(false);
        //entityTypeBuilder.Property(p => p.KeyOffer).HasColumnType("uniqueidentifier").ValueGeneratedNever().IsRequired(false);
        //entityTypeBuilder.Property(p => p.LatCatchedUser).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.LngCatchedUser).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.LatSendDone).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.LngSendDone).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.LatSendInvite).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.LngSendInvite).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.LatCancel).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.LngCancel).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.VehiclePrivate).HasColumnType("NVARCHAR(50)").IsRequired(false);
        //entityTypeBuilder.Property(p => p.SCarType).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.CancelOverTime).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.TypeDone).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.CreatedDate).HasColumnType("DATETIME").IsRequired(false);
        //entityTypeBuilder.Property(p => p.ReceivedBook).HasColumnType("BIT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.FromAddress).HasColumnType("NVARCHAR(1000)").IsRequired(false);
        //entityTypeBuilder.Property(p => p.SourceCancel).HasColumnType("BIT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.CatchedTime).HasColumnType("DATETIME").IsRequired(false);
        //entityTypeBuilder.Property(p => p.ValueSaleOffCode).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.TripPrice).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.MoneyExtend).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.MoneyExtendByTime).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.MoneyExtendFromDriver).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.WaitMoney).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.ManualMoney).HasColumnType("FLOAT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.TripSegments).HasColumnType("NTEXT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.SentTime).HasColumnType("DATETIME").IsRequired(false);
        //entityTypeBuilder.Property(p => p.FK_CompanyId).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.ComLandmarkId).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.Employee).HasColumnType("uniqueidentifier").ValueGeneratedNever().IsRequired(false);
        //entityTypeBuilder.Property(p => p.LotIndex).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.SyncFromBak).HasColumnType("BIT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.CardMoney).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.IsPaid).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.IsDriverPaid).HasColumnType("BIT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.DriverName).HasColumnType("NVARCHAR(100)").IsRequired(false);
        //entityTypeBuilder.Property(p => p.IsVirtualRadio).HasColumnType("BIT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.TotalDone).HasColumnType("INT").IsRequired(false);
        //entityTypeBuilder.Property(p => p.TotalCancel).HasColumnType("INT").IsRequired(false);
    }
}
