<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.2</Version>
    <Title>Logger ELK . Send Log to ELK TMS</Title>
    <Authors>longpv2</Authors>
    <Company>BAGPS</Company>
    <Product>TMS</Product>
    <Description>Send Log Service System . Manage by ELK TMS</Description>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
    <PackageTags>log logger logging</PackageTags>
    <PackageIcon>LOG ELK.jpg</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\download\LOG ELK.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="Readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
