<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoggerELK\LoggerELK.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LoggerELK">
      <HintPath>bin\Debug\net8.0\LoggerELK.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
